### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by ibmbootcamp** [seek-oss/html-sketchapp-cli#31]
I am getting the error below after installing the plugin.

/usr/local/lib/node_modules/html-sketchapp-cli/bin/cli.js:59
  }, async argv => {
     ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by markdalgleish** [comment]
What version of Node are you running?

**Comment by ibmbootcamp** [comment]
Hi Thanks a lot. Turned out to be my node version. I have upgraded to 5.6 and the issue solved but it lead me into another issue on mac which is related to permissions on the installation of puppeteer. I managed to resolve that using following command:

sudo npm install --global html-sketchapp-cli  --unsafe-perm=true
