### ISSUE TITLE
cli.js syntax error running install command

### ISSUE THREAD

**Issue by mattwilkerson1121** [seek-oss/html-sketchapp-cli#47]
I'm on a mac running macOS 10.13.4 (17E202) Kernel Version:Darwin 17.5.0 and when I run the html-sketchapp install command in terminal I am getting this error message kicked back.

/usr/local/lib/node_modules/html-sketchapp-cli/bin/cli.js:64
}, async argv => {
     ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by markdalgleish** [comment]
This is because you're on an older version of Node without async/await support (<7.6).
