### ISSUE TITLE
install fails, cannot find module puppeteer

### ISSUE THREAD

**Issue by phun-ky** [seek-oss/html-sketchapp-cli#54]
```
$ node -v && npm -v
v8.11.1
5.8.0
```
Using Ubuntu Bash in Windows 10

```
$ npm install --global html-sketchapp-cli
/root/.nvm/versions/node/v8.11.1/bin/html-sketchapp -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/html-sketchapp-cli/bin/cli.js

> puppeteer@1.6.0 install /root/.nvm/versions/node/v8.11.1/lib/node_modules/html-sketchapp-cli/node_modules/puppeteer
> node install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v8.11.1/lib/node_modules/html-sketchapp-cli/node_modules/puppeteer/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.6.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-19T10_13_15_468Z-debug.log
```

This works on git-bash though :( , using `npx` does not help. I also tried to install `puppeteer` globally, no luck

**Comment by phun-ky** [comment]
` npm -g install html-sketchapp-cli --unsafe-perm` does the trick somehow

**Comment by phun-ky** [comment]
Nope, stuck at this now:

    $ html-sketchapp --url http://localhost:8080/2.0.9/ --out-dir dist/
    Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
        at assert (/npm/node_modules/html-sketchapp-cli/node_modules/puppeteer/lib/helper.js:282:11)
        at Function.launch (/npm/node_modules/html-sketchapp-cli/node_modules/puppeteer/lib/Launcher.js:106:7)
        at <anonymous>
