### ISSUE TITLE
Syntax error while html-sketchapp install

### ISSUE THREAD

**Issue by anilkk** [seek-oss/html-sketchapp-cli#7]
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

Looked into the issue https://github.com/seek-oss/html-sketchapp-cli/issues/5.
Looks like this one is different issue

**Comment by markdalgleish** [comment]
Which version of node are you running?

**Comment by anilkk** [comment]
node v6.11.2 on macOS High Sierra

**Comment by markdalgleish** [comment]
Sorry, but this project requires at least v7.6 of node, as specified in our package.json: https://github.com/seek-oss/html-sketchapp-cli/blob/01a50a11a6ec6e1bf9810e92bf0c79139a9a1b5c/package.json#L6

**Comment by anilkk** [comment]
@markdalgleish Thanks.
